EXTENDS:
    - "https://raw.githubusercontent.com/llaville/.github/refs/heads/master/.mega-linter-base.yml"
ENABLE:
    - ACTION
    - DOCKERFILE
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_PRETTIER
    - JSON_V8R
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_BUILTIN
    - PHP_PHPCSFIXER
    - PHP_PSALM
    - YAML_V8R
DOCKERFILE_HADOLINT_ARGUMENTS: "-t error"
PHP_PHPSTAN_DISABLE_ERRORS: false
PRINT_ALL_FILES: false
