= UmlWriter

**UmlWriter** is a library that
adds the ability to generate UML class diagram in both Graphviz and PlantUML formats.

You have also choice to switch between two reverse-engine :

* https://github.com/llaville/php-reflect[Bartlett\Reflect]
* https://github.com/Andrewsville/PHP-Token-Reflection[Andrewsville\TokenReflection]

Follow development on the http://php5.laurent-laville.org/umlwriter/blog/[official Blog].

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/umlwriter-1.3.0.phar[1.3.0]
that has all required (as well as some optional) dependencies of UmlWriter bundled in a single file.

* install latest version with composer, as follow: `composer require bartlett/umlwriter ^1.2`

== Documentation

The documentation for UmlWriter 1.2 is available
in http://php5.laurent-laville.org/umlwriter/manual/1.2/en/[English]
to read it online or download to read it later (multiple formats).

AsciiDoc source code are available on `docs` folder of the repository.

== Authors

* Laurent Laville

== License

This handler is licensed under the BSD-3-clauses License - see the `LICENSE` file for details
