ifndef::basebackend-docbook[]

= User Guide
:description: Installing UmlWriter
include::revision.asciidoc[]
include::attributes.asciidoc[]

endif::basebackend-docbook[]

== Installation

[role="lead"]
UmlWriter may be installed in several ways, choose your favorite.


=== Requirements

Before you install PHP [label label-primary]#UmlWriter#, you will need an operating system
with http://www.php.net[PHP] 5.4.0 or later installed,

[label label-primary]#UmlWriter# requires the
http://www.php.net/manual/en/book.spl.php[spl] extensions.
This extension is usually compiled and enabled by default.

=== Composer

Put a file named [label label-default]#composer.json# at the root of your project, with the content below:
[source,json]
----
{
    "require": {
        "bartlett/umlwriter": "^1.2"
    }
}
----
And ask http://getcomposer.org/[Composer] to install the dependencies:
[source,bash]
----
$ php composer.phar install
----
Or just invoke Composer to install the latest version:
[source,bash]
----
$ php composer.phar require bartlett/umlwriter
----

[TIP]
====
You can also use Composer to create a new project from an existing [label label-primary]#UmlWriter# package.
This is the equivalent of doing a git clone checkout followed by a composer install of the vendors.

[source,bash]
----
$ php composer.phar create-project bartlett/umlwriter /path/to/install ^1.2
----
Where +/path/to/install+ is your install directory.
====

=== PHAR

The recommended way for newbies, or just to have a look on features of this library, is to download
a PHP Archive that contain all required dependencies of PHP [label label-primary]#UmlWriter#
bundled in a single file.

[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/umlwriter-1.2.0.phar
$ chmod +x umlwriter-1.2.0.phar
$ mv umlwriter-1.2.0.phar /usr/local/bin/umlwriter
$ umlwriter
----

You can also immediately use the PHAR after you have downloaded it.
[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/umlwriter-1.2.0.phar
$ php umlwriter-1.2.0.phar
----

ifdef::basebackend-bootstrap[]
== Next

link:user-guide&#45;&#45;commands.html["The Command-Line Interface",role="primary",icon="glyphicon-step-forward",options="block"]

************************************************
.Read more

For developers who want to extend or change UmlWriter features.

* Want to create a new processor,
have a look on link:processor-guide.html[processor]'s guide.

* Want to create a new reverse engine,
have a look on link:reflector-guide.html[reflector]'s guide.

************************************************
endif::[]
