---
name: GitHub-Pages

on:
    push:
        branches:
            - master
            - "4.0"
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@uml
        with:
            php-version: "8.1"
            destination-dir: "4.0"
            hook-script: "resources/gh-pages-hook.sh"
            force-orphan: false
            graph-uml: false
