---
name: GitHub-Pages

on:
    push:
        branches:
            - master
            - 3.x
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@master
        with:
            php-version: "8.0"
            destination-dir: 3.x
            hook-script: "resources/gh-pages-hook.sh"
            force-orphan: false
