---
name: Release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

env:
    BOX_OUTPUT: bin/umlwriter.phar
    RELEASE_NOTES: releaseNotes.md

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/llaville/box-manifest:latest

        steps:
            -   # Git Checkout
                name: Checkout
                uses: actions/checkout@v2

            -   # Build the current release changelog
                name: Build Release Notes
                run: |
                    resources/release/build.php

            -   # Build the current release with artifacts (php archive)
                name: Build Release Artifacts
                uses: docker://ghcr.io/llaville/box-manifest:latest
                with:
                    entrypoint: /usr/local/src/box-manifest/bin/box
                    args: compile

            -   # Draft a new Release
                name: Release
                uses: softprops/action-gh-release@v1
                #if: startsWith(github.ref, 'refs/tags/')
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: true
                    draft: true
                    body_path: ${{ github.workspace }}/${{ env.RELEASE_NOTES }}
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ env.BOX_OUTPUT }}
