---
name: Unit Tests

on:
    pull_request:
        branches:
            - master
            - "4.2"
        paths-ignore:
            - 'docs/**'
    workflow_call:

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}
            php-version: "8.2"

    unit_tests:
        needs: lint_files

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - 8.2
                    - 8.3

        name: UML Class Writer

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v4

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: "none"

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    composer-options: "--prefer-dist"

            -   # https://github.com/sebastianbergmann/phpunit/tree/10.5
                name: Unit tests with PHPUnit 10
                run: vendor/bin/phpunit --testdox --do-not-cache-result --no-progress
